name: geohexviz
channels:
  - conda-forge
  - defaults
  - plotly
dependencies:
  - geopandas
  - setuptools
  - python-kaleido
  - geojson
  - plotly
  - h3-py
  - pyyaml
  - rtree
  - openpyxl
  - shapely