name: CI Tests (Conda)

on:
  push:
    branches:
      - master
      - buffer
  pull_request:
    branches:
      - master

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  miniconda:
    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
            python-version: [ '3.7', '3.8' ]
    steps:
      - uses: actions/checkout@v2

      - name: Cache Conda
        uses: actions/cache@v1
        env:
          CACHE_NUMBER: 2
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('env.yml') }}

      - name: Setup Conda

        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          active-environment: my-env
          use-mamba: true

      - name: Set cache date and cache
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

        uses: actions/cache@v2
        with:
          path: ${{ matrix.prefix }}
          key: ${{ matrix.label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: mamba env update -n my-env -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Display conda info
      - shell: bash -l {0}
        run: |
          mamba info
          mamba list

      - name: Lint with flake8
        shell: bash -l {0}
        run: |
            mamba install flake8
            python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run tests with unittest
        shell: bash -l {0}
        run: |
            python -m unittest discover
